/*--------------------------------------------------------------------------------*
 * Name: Parser Look-up tree
 * Desc: function and data structures to speed up a specific string search
 *
 *         **** DO NOT AMEND THIS CODE - IT IS AUTO_GENERATED ****
 *
 * Code and table produced by:
 *            build_graph 
 *            version 0.3
 *
 *  written by Peter Antoine. 
 *
 *   **** This code can be used however you like, no claims whatsoever are ****
 *   **** placed on the auto-generated code or data, or on the code that   ****
 *   **** uses the that code or data.                                      ****
 *   **** Or, to paraphrase "Fill you're boots".                         ****
 *--------------------------------------------------------------------------------*/

#ifndef	__ICAL_STRINGS_H__
#define __ICAL_STRINGS_H__

typedef	struct
{
	char*			name;
	unsigned int	length;
} ICAL_STRINGS_STRING_TABLE;

typedef enum
{
	HNUT_ICAL_STR_BEGIN,
	HNUT_ICAL_STR_END,
	HNUT_ICAL_STR_VCALENDAR,
	HNUT_ICAL_STR_VEVENT,
	HNUT_ICAL_STR_VTODO,
	HNUT_ICAL_STR_VJOURNAL,
	HNUT_ICAL_STR_VFREEBUSY,
	HNUT_ICAL_STR_VTIMEZONE,
	HNUT_ICAL_STR_VALARM,
	HNUT_ICAL_STR_STANDARD,
	HNUT_ICAL_STR_DAYLIGHT,
	HNUT_ICAL_STR_CALSCALE,
	HNUT_ICAL_STR_METHOD,
	HNUT_ICAL_STR_PRODID,
	HNUT_ICAL_STR_VERSION,
	HNUT_ICAL_STR_ATTACH,
	HNUT_ICAL_STR_CATEGORIES,
	HNUT_ICAL_STR_CLASS,
	HNUT_ICAL_STR_COMMENT,
	HNUT_ICAL_STR_DESCRIPTION,
	HNUT_ICAL_STR_GEO,
	HNUT_ICAL_STR_LOCATION,
	HNUT_ICAL_STR_PERCENT_COMPLETE,
	HNUT_ICAL_STR_PRIORITY,
	HNUT_ICAL_STR_RESOURCES,
	HNUT_ICAL_STR_STATUS,
	HNUT_ICAL_STR_SUMMARY,
	HNUT_ICAL_STR_COMPLETED,
	HNUT_ICAL_STR_DTEND,
	HNUT_ICAL_STR_DUE,
	HNUT_ICAL_STR_DTSTART,
	HNUT_ICAL_STR_DURATION,
	HNUT_ICAL_STR_FREEBUSY,
	HNUT_ICAL_STR_TRANSP,
	HNUT_ICAL_STR_TZID,
	HNUT_ICAL_STR_TZNAME,
	HNUT_ICAL_STR_TZOFFSETFROM,
	HNUT_ICAL_STR_TZOFFSETTO,
	HNUT_ICAL_STR_TZURL,
	HNUT_ICAL_STR_ATTENDEE,
	HNUT_ICAL_STR_CONTACT,
	HNUT_ICAL_STR_ORGANIZER,
	HNUT_ICAL_STR_RECURRENCE_ID,
	HNUT_ICAL_STR_RELATED_TO,
	HNUT_ICAL_STR_URL,
	HNUT_ICAL_STR_UID,
	HNUT_ICAL_STR_EXDATE,
	HNUT_ICAL_STR_EXRULE,
	HNUT_ICAL_STR_RDATE,
	HNUT_ICAL_STR_RRULE,
	HNUT_ICAL_STR_ACTION,
	HNUT_ICAL_STR_REPEAT,
	HNUT_ICAL_STR_TRIGGER,
	HNUT_ICAL_STR_CREATED,
	HNUT_ICAL_STR_DTSTAMP,
	HNUT_ICAL_STR_LAST_MODIFIED,
	HNUT_ICAL_STR_SEQUENCE,
	HNUT_ICAL_STR_REQUEST_STATUS,
	HNUT_ICAL_STR_ALTREP,
	HNUT_ICAL_STR_CN,
	HNUT_ICAL_STR_CUTYPE,
	HNUT_ICAL_STR_DELEGATED_FROM,
	HNUT_ICAL_STR_DELEGATED_TO,
	HNUT_ICAL_STR_DIR,
	HNUT_ICAL_STR_ENCODING,
	HNUT_ICAL_STR_FMTTYPE,
	HNUT_ICAL_STR_FBTYPE,
	HNUT_ICAL_STR_LANGUAGE,
	HNUT_ICAL_STR_MEMBER,
	HNUT_ICAL_STR_PARTSTAT,
	HNUT_ICAL_STR_RANGE,
	HNUT_ICAL_STR_RELATED,
	HNUT_ICAL_STR_RELTYPE,
	HNUT_ICAL_STR_ROLE,
	HNUT_ICAL_STR_RSVP,
	HNUT_ICAL_STR_SENT_BY,
	HNUT_ICAL_STR_VALUE,
	HNUT_ICAL_STR_BINARY,
	HNUT_ICAL_STR_BOOLEAN,
	HNUT_ICAL_STR_CAL_ADDRESS,
	HNUT_ICAL_STR_DATE,
	HNUT_ICAL_STR_DATE_TIME,
	HNUT_ICAL_STR_FLOAT,
	HNUT_ICAL_STR_INTEGER,
	HNUT_ICAL_STR_PERIOD,
	HNUT_ICAL_STR_RECUR,
	HNUT_ICAL_STR_TEXT,
	HNUT_ICAL_STR_TIME,
	HNUT_ICAL_STR_URI,
	HNUT_ICAL_STR_UTC_OFFSET,
	HNUT_ICAL_STR_INDIVIDUAL,
	HNUT_ICAL_STR_GROUP,
	HNUT_ICAL_STR_RESOURCE,
	HNUT_ICAL_STR_ROOM,
	HNUT_ICAL_STR_UNKNOWN,
	HNUT_ICAL_STR_FREE,
	HNUT_ICAL_STR_BUSY,
	HNUT_ICAL_STR_BUSY_UNAVAILABLE,
	HNUT_ICAL_STR_BUSY_TENTATIVE,
	HNUT_ICAL_STR_NEEDS_ACTION,
	HNUT_ICAL_STR_ACCEPTED,
	HNUT_ICAL_STR_DECLINED,
	HNUT_ICAL_STR_TENTATIVE,
	HNUT_ICAL_STR_DELEGATED,
	HNUT_ICAL_STR_IN_PROCESS,
	HNUT_ICAL_STR_CHILD,
	HNUT_ICAL_STR_PARENT,
	HNUT_ICAL_STR_SIBLING,
	HNUT_ICAL_STR_CHAIR,
	HNUT_ICAL_STR_REQ_PARTICIPANT,
	HNUT_ICAL_STR_OPT_PARTICIPANT,
	HNUT_ICAL_STR_NON_PARTICIPANT,
	HNUT_ICAL_STR_AUDIO,
	HNUT_ICAL_STR_DISPLAY,
	HNUT_ICAL_STR_EMAIL,
	HNUT_ICAL_STR_PROCEDURE,
	HNUT_ICAL_STR_PUBLIC,
	HNUT_ICAL_STR_PRIVATE,
	HNUT_ICAL_STR_CONFIDENTIAL,
	HNUT_ICAL_STR_8BIT,
	HNUT_ICAL_STR_BASE64	
} HNUT_ICAL_STR_ICAL_STRINGS;

int	ical_strings_check_word(char* word);

#endif
